mqtt:
  enabled: True
  host: core-mosquitto
  user: mqtt-user
  password: password
  port: 1883

record:
  enabled: True
  retain:
    days: 1
    mode: active_objects
  events:
    retain:
      default: 30
      mode: motion
detect:
  annotation_offset: -800
detectors:
  coral1:
    type: edgetpu
    device: pci:0
snapshots:
  enabled: true
  retain:
    default: 1

timestamp_style:
  position: tl
  format: '%m/%d/%Y %H:%M:%S'
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

go2rtc:
  streams:
    kids_room:
    - rtsp://admin:password@10.0.0.56/Preview_01_main
    kids_room_sub:
    - rtsp://admin:password@10.0.0.56/Preview_01_sub
    living_room:
    - rtsp://admin:password@10.0.0.54/Preview_01_main
    living_room_sub:
    - rtsp://admin:password@10.0.0.54/Preview_01_sub
    flood_light:
    - rtsp://admin:password@10.0.0.48/Preview_01_main
    flood_light_sub:
    - rtsp://admin:password@10.0.0.48/Preview_01_sub
    front_porch:
    - rtsp://admin:password@10.0.0.28/Preview_01_main
    front_porch_sub:
    - rtsp://admin:password@10.0.0.28/Preview_01_sub
    nana_porch:
    - rtsp://admin:password@10.0.0.28/Preview_05_main
    nana_porch_sub:
    - rtsp://admin:password@10.0.0.28/Preview_05_sub
    backyard:
    - rtsp://admin:password@10.0.0.28/Preview_04_main
    backyard_sub:
    - rtsp://admin:password@10.0.0.28/Preview_04_sub
    east_side:
    - rtsp://admin:password@10.0.0.28/Preview_03_main
    east_side_sub:
    - rtsp://admin:password@10.0.0.28/Preview_03_sub
    west_side:
    - rtsp://admin:password@10.0.0.28/Preview_24_main
    west_side_sub:
    - rtsp://admin:password@10.0.0.28/Preview_24_sub

ffmpeg:
  hwaccel_args: preset-vaapi

cameras: # Reolink Camera
  Kids_Room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kids_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kids_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 896
      height: 512
      fps: 10
    objects:
      track:
        - person
        - dog
  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/living_room_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 896
      height: 512
      fps: 10
    objects:
      track:
        - person
        - dog
  Flood_Light:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/flood_light
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/flood_light_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1536
      height: 576
      fps: 15
    objects:
      track:
        - person
        - dog
  Front_Porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_porch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - dog
  Nanas_Porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nana_porch
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/nana_porch_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - dog
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 1536
      height: 432
      fps: 15
    objects:
      track:
        - person
        - dog
  West_Side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/west_side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/west_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - dog
  East_Side:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/east_side
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/east_side_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac
    detect:
      width: 640
      height: 360
      fps: 7
    objects:
      track:
        - person
        - dog

logger:
  # Optional: Default log verbosity (default: shown below)
  default: debug
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug
