# not tested
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /home/brandon/docker/nginx-proxy/data:/data
      - /home/brandon/docker/nginx-proxy/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
  ddns:
    image: mxmlndml/cloudflare-dynamic-dns:latest
    container_name: cloudflare-dynamic-dns
    restart: unless-stopped
    environment:
      - "API_KEY=${API_KEY}"
      - "ZONE_ID=${ZONE_ID}"
      - "DOMAIN_NAMES=example.com,dyndns.example.com"
      - "RECORD_TYPES=A"
      - "INTERVAL=5"
networks:
  default:
    external: true
    name: nginx-proxy
